global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
# - "first.rules"
# - "second.rules"

scrape_configs:
  - job_name: prometheus, loulila
    static_configs:
      - targets:
          - "localhost:9090"
          - "prometheus-gateway:9091"
